services:
  aspiresync:
    # image: aspirepress/apiresync:latest

    build:
      context: .
      dockerfile: docker/Dockerfile
      target: devbuild

    environment:
      DB_HOST: db
      DB_NAME: aspiresync
      DB_USER: aspiresync
      DB_PASS: password
      DB_SCHEMA: public

    networks:
      - app-net

    volumes:
      - ./code:/opt/aspiresync

    # having an entrypoint is annoying at this early stage, that's for a prod setup
    # entrypoint: ['/opt/aspiresync/bin/aspiresync']

    tty: true   # keeps the container running

  # https://hub.docker.com/_/postgres
  db:
    image: postgres:16
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: password

    ports:
      - "${LOCAL_DB_PORT:-54321}:5432"

    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./docker/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh

    networks:
      - app-net

volumes:
  dbdata: ~

networks:
  app-net: ~
